
name: Tourism MLOps Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-and-train:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Data Preparation
        run: |
          python tourism_project/model_building/prep.py

      - name: Train Model
        run: |
          python tourism_project/model_building/train.py

      - name: Verify Deployment Files
        run: |
          ls tourism_project/deployment
